# Generated by Django 3.2.25 on 2024-05-31 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0002_auto_20240531_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_comments1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.bill')),
            ],
        ),
    ]
