# Generated by Django 3.2.25 on 2024-05-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0003_bill_comments1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill_comments1',
        ),
    ]
