# Generated by Django 3.2.25 on 2024-06-03 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0005_auto_20240531_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bankaccno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='checkno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='upi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('action', models.CharField(default='Created', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.expense')),
                ('logindetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='expense_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.expense')),
                ('logindetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
