# Generated by Django 3.2.25 on 2024-06-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_auto_20240603_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company_Staff.pricelist'),
        ),
        migrations.AddField(
            model_name='bill',
            name='price_list_applied',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='repeat_every',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.companyrepeatevery'),
        ),
    ]
