# Generated by Django 3.2.25 on 2024-06-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_auto_20240603_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Saved', 'Saved')], max_length=10, null=True),
        ),
    ]
